### PR TITLE
Package that generates resource lists based on Azure/azure-resource-manager-schemas

### PR DESCRIPTION
**Pull request by CodeRunRepeat**
In `packages/schema-generator', contains two different approaches to generating schemas, both starting with https://www.github.com/Azure/azure-resource-manager-schemas.

(Recommended) `schemas-repo.ts` builds a list of all schemas listed in Azure/azure-resource-manager-schemas:
* Only version folders in the form 2xxx-xx-xx are included
* Preview folders are excluded
* Keeps the latest version for each service
* Emits `out/schema-config-repo.json`

(Alternative, not recommended) `schemas-deployment-template.ts` does the following:
* Finds all version directories under schemas that contain a deploymentTemplate.json file
* Extracts the schema references from the file, de-dupes, and removes preview
* Emits a schema-config.json file for each deployment template in `out`.

### CODE REVIEW

**Comment by aheumaier** [comment]
Any specific reason we call the script `index.ts` - does it make sense to rather have functional name ?

**Comment by CodeRunRepeat** [comment]
> Any specific reason we call the script `index.ts` - does it make sense to rather have functional name ?

Renamed to schemas-deployment-template.ts

**Comment by aheumaier** [comment]
It makes sense to me to add this to  new package like `schemaConfigGenerator` in `tools`. `tools` itself is a repo reserved name and should not be a package itself.

**Comment by aheumaier** [comment]
If we can use dynamicly created files from this package it is safe to leave out ephermeral results

**Review by aheumaier — APPROVED** [review]

**Pull request merged**
